version: "3.8"

services:

  forum-api:
    restart: always
    depends_on:
      - broker
      - forum-db
    build: 
      context: src/server
      dockerfile: Services/Dockerfile
      args:
        project_name: Forum.API
    container_name: forum-api
  
  forum-migrator:
    restart: on-failure
    depends_on:
      - forum-db
    build:
      context: src/server
      dockerfile: Forum.Migrator/Dockerfile
    container_name: forum-migrator

  forum-queue-listener:
    restart: always
    depends_on:
      - broker
      - forum-db
    build:
      context: src/server
      dockerfile: Services/Dockerfile
      args:
        project_name: Forum.Consumer
    container_name: forum-queue-listener

  forum-db:
    image: ${FORUM_DB_IMAGE}
    container_name: forum-db

  metadata-api:
    restart: always
    depends_on:
      - metadata-db
      - broker
      - cache
    build:
      context: src/server
      dockerfile: Services/Dockerfile
      args:
        project_name: Metadata.API
    container_name: metadata-api
    
  metadata-db:
    image: ${METADATA_DB_IMAGE}
    container_name: metadata-db

  file-api:
    restart: always
    depends_on:
      - s3
    build:
      context: src/server
      dockerfile: Services/Dockerfile
      args:
        project_name: File.API
    container_name: file-api

  file-metadata-queue-listener:
    restart: always
    depends_on:
      - metadata-db
      - broker
      - s3
      - cache
    build:
      context: src/server
      dockerfile: Services/Dockerfile
      args:
        project_name: FileMetadata.Consumer
    container_name: file-metadata-queue-listener

  web-front:
    restart: always
    build:
      context: src/client
      dockerfile: Dockerfile
    container_name: web-front
  
  broker:
    image: ${BROKER_IMAGE}
    container_name: broker

  s3:
    image: ${S3_IMAGE}
    container_name: s3
  
  cache:
    image: ${CACHE_IMAGE}
    container_name: cache